
platform :ios, '12.0'
use_frameworks!
install!'cocoapods', :warn_for_unused_master_specs_repo => false

target 'AnyCoder_Example' do
  pod 'AnyCoder', :path => '../'

  target 'AnyCoder_Tests' do
    inherit! :search_paths

    
  end
end
